# Generated by Django 5.2.17 on 2026-09-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_education_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_url',
            field=models.URLField(blank=True),
        ),
    ]
